In [1]:
import numpy as np

# Why need numpy if python has list?

# Problem 1:

# Performance issue:
Imagine if a transaction dataset has 10 million transactions and if you have to increase every transaction amount by 18 percent . 
**Python** goes one by one and imagine the time it takes a disastrous amount of time is wasted
**Numpy** solves this by doing whole array operation reducing the time .This property of **Numpy** is called **Vectorization**.. 

# Problem 2:
## Memory :
In python list internally everything is treated as a seperate python object. More memory occupied
**Numpy** solves this easy as in numpy its ***Same data type ad continuous  memory block***


# Introduction to NumPy

NumPy (Numerical Python) is a Python library used for
fast numerical computations.

It provides a powerful array object that allows efficient
mathematical operations on large datasets.

NumPy is the foundation for many data science libraries
including pandas, scikit-learn and deep learning frameworks.


In [3]:
import numpy as np
np.array(object)

array(<class 'object'>, dtype=object)

In [4]:
import numpy as np
numbers = np.array([10,20,30,40])
print(numbers)

[10 20 30 40]


In [6]:
# checking the type of the array 
type(numbers)

numpy.ndarray

## Creating NumPy Arrays

Syntax:

np.array(object)

np.array converts Python sequences such as lists
into efficient NumPy ndarray objects.

Example:

numbers = np.array([10,20,30,40])

Advantages:
- Faster computation
- Less memory usage
- Supports mathematical operations

In [7]:
import numpy as np
a = np.array([5,10,15])
print(type(a))

<class 'numpy.ndarray'>


In [12]:
import numpy as np
a = np.array([10,12,14,16])
print(a * 2) 
print(a.dtype) #  tells what data type or data values are stored in the numpy array

[20 24 28 32]
int64


# Q: Why is NumPy faster than Python lists?

 ### Answer:

NumPy arrays store elements of the same datatype in contiguous memory locations and perform operations using optimized C implementations. This allows vectorized computation, making numerical operations much faster than Python loops over lists.

## NumPy dtype

dtype represents the datatype of elements stored inside a NumPy array.

Examples:

Integer values:
int64

Decimal values:
float64

Strings:
Unicode/string type


dtype is important because numerical operations in
data science and machine learning require correct data types.

In [15]:
import numpy as np
data = np.array([10,20,30,40,50])
print(data.shape) # shape is an attribute not a function

(5,)


In [21]:
import numpy as np
data = np.array([10,20,30,40,50])
print(data.ndim) # ndim tells abt the dimension of the array or the numpy array we have.
print(data.size) # we only care abt the no of elements in the array  then we use the size attribute

1
5


# NumPy Array Properties

## shape

shape gives the dimensions of an array.

It tells the number of rows and columns.

Example:
(100,5)

means:
100 observations
5 features


## ndim

ndim represents the number of dimensions.

1D → vector
2D → matrix
3D → image/tensor


## size

size gives the total number of elements present.


## dtype

dtype represents the datatype of values stored.

In [23]:
import numpy as np
b=np.array([
[1,2,3],
[4,5,6],
[7,8,9]
])

print(b.shape) # python returns it as a tuple as shape can have multiple values
print(b.ndim)
print(b.size)

(3, 3)
2
9


## np.zeros()

### Why do we need it?

`np.zeros()` creates a NumPy array filled with zeros. It is useful when we need to initialize arrays before storing or updating values.

### Syntax

```python
np.zeros(shape, dtype=float)


## np.ones()

Creates a NumPy array filled with ones.

### Syntax

```python
np.ones(shape, dtype=float)
```

Example:

```python
np.ones((2,3))
```

Used for initialization, testing, and machine learning computations.

## np.arange()

Creates a NumPy array containing evenly spaced values.

### Syntax

```python
np.arange(start, stop, step)
```

The `stop` value is excluded.

Example:

```python
np.arange(0,10,2)
# [0 2 4 6 8]
```

## np.linspace()

Creates a fixed number of evenly spaced values between two endpoints.

### Syntax

```python
np.linspace(start, stop, num)
```

Example:

```python
np.linspace(0,1,5)
# [0.   0.25 0.5  0.75 1.  ]
```

Unlike `arange()`, the stop value is included by default.

# NumPy Indexing

## Why do we need indexing?

Indexing allows us to access specific elements from a NumPy array.

## Syntax

array[index]

NumPy uses zero-based indexing.

Example:

transactions[0]

returns the first element.

## Negative Indexing

Negative indexes access elements from the end.

Example:

transactions[-1]

returns the last element.

## Usage

Used for selecting specific observations,
extracting values, and analyzing subsets of data.


In [8]:
import numpy as np
amounts = np.array([100,200,300,400,500])
print(amounts[1:4]) # array slicing is start:stop:step stop value is excluded..
print(amounts[:3])  # it defaultly means we start from 0 and end at 2 
print(amounts[1:]) # it tells the starting index but final stop value is not mentioned so it goes till the very last
print(amounts[::2]) # an example to just have the step value

[200 300 400]
[100 200 300]
[200 300 400 500]
[100 300 500]


# NumPy Slicing

## Why do we need it?

Slicing allows selecting a range or subset of elements
from a NumPy array.

## Syntax

array[start:stop:step]

start → beginning index
stop → ending index (excluded)
step → interval between elements

## Example

arr[1:4]

returns elements from index 1 to 3.

## Usage

Used for selecting portions of datasets,
sampling data, and analyzing subsets.

In [9]:
import numpy as np

a = np.array([10,20,30,40,50,60])

print(a[2:5])
print(a[:4])
print(a[::3])

[30 40 50]
[10 20 30 40]
[10 40]


# Boolean Indexing

## Why?

Boolean indexing filters data based on conditions.

## Syntax

```python
array[condition]
```

## Example

```python
amounts[amounts > 1000]
```

Returns only the values that satisfy the condition.

## Usage

- Data filtering
- Removing outliers
- Selecting records
- EDA

# Aggregate functions in numpy:



| Function | Purpose |
|----------|----------|
| np.sum() | Total of values |
| np.mean() | Average |
| np.min() | Smallest value |
| np.max() | Largest value |
| np.std() | Standard deviation (spread) |
| np.var() | Variance |
| np.argmax() | Index of maximum value |
| np.argmin() | Index of minimum value |

These functions are heavily used during Exploratory Data Analysis (EDA) to summarize numerical data.

In [4]:
import numpy as np
d = np.array([20,40,10,70,50])
print(np.sum(d))
print(np.mean(d))
print(np.std(d))
print(np.min(d))
print(np.max(d))
print(np.var(d))
print(np.argmin(d))
print(np.argmax(d))

190
38.0
21.354156504062622
10
70
456.0
2
3


# Broadcasting

## Why?

Broadcasting allows NumPy to perform arithmetic operations on arrays of different but compatible shapes without writing loops.

## Example

```python
a = np.array([10,20,30])

a + 5
```

Output:

```text
[15 25 35]
```

NumPy conceptually broadcasts `5` to `[5,5,5]`.

## Usage

- Data normalization
- Scaling
- Feature transformations
- Machine learning preprocessing

## Important Notes

- Broadcasting is automatic.
- It requires compatible shapes.
- It improves performance by avoiding explicit Python loops.

In [5]:
import numpy as np
a = np.array([5,10,15])
b = np.array([2,4,6])
print(a + b)
print(a * 3)

[ 7 14 21]
[15 30 45]


In [6]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6]
])
b = np.array([10,20,30])
print(a + b)

[[11 22 33]
 [14 25 36]]


In [7]:
import numpy as np
a = np.array([10,20,30,40,50,60])
b = a.reshape((2,3))
print(b)

[[10 20 30]
 [40 50 60]]


In [ ]:
import numpy as m